#ifndef ENUM_SCREEN_CALLBACKS_H
#define ENUM_SCREEN_CALLBACKS_H
enum class EnumScreenCallback
{
    BUTTON_DISARMED,
    BUTTON_ARMED,
    BUTTON_MOTORISED,
    BUTTON_WALK,
    BUTTON_SQUAT,
    BUTTON_AUTOCALIB,
    BUTTON_4F,
    BUTTON_5F8,
    BUTTON_5F10,
    BUTTON_6F,
    BUTTON_PID0,
    BUTTON_PID1,
    BUTTON_PID2,
    BUTTON_SAVE_PID,
    P_SLIDER,
    P_INDICATOR
};

#endif